In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10 , (3,4))

In [3]:
arr

array([[4, 6, 8, 7],
       [3, 5, 7, 6],
       [2, 7, 1, 6]])

In [4]:
arr.reshape(6,2)

array([[4, 6],
       [8, 7],
       [3, 5],
       [7, 6],
       [2, 7],
       [1, 6]])

In [5]:
arr.reshape(2,6)

array([[4, 6, 8, 7, 3, 5],
       [7, 6, 2, 7, 1, 6]])

In [6]:
arr.reshape(6,-454)

array([[4, 6],
       [8, 7],
       [3, 5],
       [7, 6],
       [2, 7],
       [1, 6]])

In [7]:
arr.T

array([[4, 3, 2],
       [6, 5, 7],
       [8, 7, 1],
       [7, 6, 6]])

In [8]:
arr

array([[4, 6, 8, 7],
       [3, 5, 7, 6],
       [2, 7, 1, 6]])

In [9]:
arr.flatten()

array([4, 6, 8, 7, 3, 5, 7, 6, 2, 7, 1, 6])

In [10]:
arr1 = np.array([1,2,3,3,4])

In [11]:
arr1.ndim

1

In [13]:
np.expand_dims(arr1,axis=1)
# axis=1 mean change the axis to row
# expand dimension 

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [16]:
np.expand_dims(arr1,axis=0)
# axis=0 mean change the axis to column
# expand dimension 

array([[1, 2, 3, 3, 4]])

In [18]:
np.squeeze(arr)

array([[4, 6, 8, 7],
       [3, 5, 7, 6],
       [2, 7, 1, 6]])

In [19]:
data = np.array([[1],[2],[3]])

In [20]:
data

array([[1],
       [2],
       [3]])

In [21]:
type(data)

numpy.ndarray

In [22]:
data.ndim

2

In [25]:
ad=np.squeeze(data)

In [27]:
ad.ndim

1

In [29]:
arr1

array([1, 2, 3, 3, 4])

In [31]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [32]:
np.roll(arr1,2)

array([3, 4, 1, 2, 3])

In [33]:
arr1

array([1, 2, 3, 3, 4])

In [35]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [36]:
#Numpy - Binary Operators.

In [37]:
arr1 = np.random.randint(1,10,(3,4))

In [38]:
arr2 = np.random.randint(1,10,(3,4))

In [39]:
arr1

array([[8, 4, 1, 2],
       [8, 1, 7, 2],
       [9, 1, 3, 5]])

In [40]:
arr2

array([[2, 4, 3, 4],
       [2, 5, 6, 5],
       [9, 7, 8, 3]])

In [41]:
arr1+arr2

array([[10,  8,  4,  6],
       [10,  6, 13,  7],
       [18,  8, 11,  8]])

In [42]:
arr1-arr2

array([[ 6,  0, -2, -2],
       [ 6, -4,  1, -3],
       [ 0, -6, -5,  2]])

In [43]:
arr1*arr2

array([[16, 16,  3,  8],
       [16,  5, 42, 10],
       [81,  7, 24, 15]])

In [44]:
arr1/arr2

array([[4.        , 1.        , 0.33333333, 0.5       ],
       [4.        , 0.2       , 1.16666667, 0.4       ],
       [1.        , 0.14285714, 0.375     , 1.66666667]])

In [45]:
arr1%arr2

array([[0, 0, 1, 2],
       [0, 1, 1, 2],
       [0, 1, 3, 2]], dtype=int32)

In [46]:
arr1**arr2

array([[       64,       256,         1,        16],
       [       64,         1,    117649,        32],
       [387420489,         1,      6561,       125]], dtype=int32)

In [47]:
arr1 & arr2

array([[0, 4, 1, 0],
       [0, 1, 6, 0],
       [9, 1, 0, 1]], dtype=int32)

In [48]:
arr1

array([[8, 4, 1, 2],
       [8, 1, 7, 2],
       [9, 1, 3, 5]])

In [49]:
arr2 

array([[2, 4, 3, 4],
       [2, 5, 6, 5],
       [9, 7, 8, 3]])

In [50]:
~arr1

array([[ -9,  -5,  -2,  -3],
       [ -9,  -2,  -8,  -3],
       [-10,  -2,  -4,  -6]], dtype=int32)

In [51]:
arr1|arr2

array([[10,  4,  3,  6],
       [10,  5,  7,  7],
       [ 9,  7, 11,  7]], dtype=int32)

In [52]:
arr1>arr2

array([[ True, False, False, False],
       [ True, False,  True, False],
       [False, False, False,  True]])

In [53]:
#Numpy - String Functions.

In [54]:
arr = np.array(['Krishna' , "Shiv"])

In [55]:
arr

array(['Krishna', 'Shiv'], dtype='<U7')

In [57]:
np.char.upper(arr)

array(['KRISHNA', 'SHIV'], dtype='<U7')

In [58]:
np.char.title(arr)

array(['Krishna', 'Shiv'], dtype='<U7')

In [60]:
np.char.capitalize(arr)

array(['Krishna', 'Shiv'], dtype='<U7')

In [61]:
#Numpy - Mathematical Functions.

In [62]:
arr1

array([[8, 4, 1, 2],
       [8, 1, 7, 2],
       [9, 1, 3, 5]])

In [63]:
np.sin(arr1)

array([[ 0.98935825, -0.7568025 ,  0.84147098,  0.90929743],
       [ 0.98935825,  0.84147098,  0.6569866 ,  0.90929743],
       [ 0.41211849,  0.84147098,  0.14112001, -0.95892427]])

In [64]:
np.cos(arr1)

array([[-0.14550003, -0.65364362,  0.54030231, -0.41614684],
       [-0.14550003,  0.54030231,  0.75390225, -0.41614684],
       [-0.91113026,  0.54030231, -0.9899925 ,  0.28366219]])

In [65]:
np.tan(arr1)

array([[-6.79971146,  1.15782128,  1.55740772, -2.18503986],
       [-6.79971146,  1.55740772,  0.87144798, -2.18503986],
       [-0.45231566,  1.55740772, -0.14254654, -3.38051501]])

In [67]:
np.tanh(arr1)

array([[0.99999977, 0.9993293 , 0.76159416, 0.96402758],
       [0.99999977, 0.76159416, 0.99999834, 0.96402758],
       [0.99999997, 0.76159416, 0.99505475, 0.9999092 ]])

In [68]:
np.log10(arr1)

array([[0.90308999, 0.60205999, 0.        , 0.30103   ],
       [0.90308999, 0.        , 0.84509804, 0.30103   ],
       [0.95424251, 0.        , 0.47712125, 0.69897   ]])

In [69]:
np.exp(arr1)

array([[2.98095799e+03, 5.45981500e+01, 2.71828183e+00, 7.38905610e+00],
       [2.98095799e+03, 2.71828183e+00, 1.09663316e+03, 7.38905610e+00],
       [8.10308393e+03, 2.71828183e+00, 2.00855369e+01, 1.48413159e+02]])

In [70]:
np.sqrt(arr1)

array([[2.82842712, 2.        , 1.        , 1.41421356],
       [2.82842712, 1.        , 2.64575131, 1.41421356],
       [3.        , 1.        , 1.73205081, 2.23606798]])

In [72]:
np.power(arr1,2)

array([[64, 16,  1,  4],
       [64,  1, 49,  4],
       [81,  1,  9, 25]], dtype=int32)

In [73]:
np.mean(arr1)

4.25

In [74]:
np.median(arr1)

3.5

In [75]:
np.std(arr1)

2.9190466480228325

In [76]:
np.var(arr1)

8.520833333333334

In [77]:
np.min(arr1)

1

In [78]:
np.max(arr1)

9