In [1]:
import numpy as np

In [2]:
arr = np.array([4,3,4,5,6,72,3,3,455,5,6,6])

In [3]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [4]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [6]:
np.searchsorted(arr ,34)
# where i can put the 34, what will be the index of 34

12

In [7]:
arr1=np.array([0,345,454,0,0,0,0,0])

In [8]:
arr1

array([  0, 345, 454,   0,   0,   0,   0,   0])

In [10]:
np.count_nonzero(arr1)
# tell us how many data are not zero

2

In [11]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [13]:
np.where(arr>6)
# index no displayed where the condition satisfied

(array([5, 8], dtype=int64),)

In [15]:
np.extract(arr>3,arr)

array([  4,   4,   5,   6,  72, 455,   5,   6,   6])

In [16]:
#Numpy - Byte Swapping.
# represent the in the byte

In [17]:
arr.byteswap()

array([  67108864,   50331648,   67108864,   83886080,  100663296,
       1207959552,   50331648,   50331648, -956235776,   83886080,
        100663296,  100663296])

In [18]:
#Numpy - Copies &Views.

In [19]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [20]:
a=np.copy(arr)

In [21]:
a

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [22]:
b=arr.view()

In [23]:
b

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [24]:
b[0]=55

In [25]:
b

array([ 55,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [26]:
arr

array([ 55,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [27]:
#Numpy - Matrix Library.

In [28]:
import numpy.matlib as nm

In [29]:
nm.zeros(5
        )

matrix([[0., 0., 0., 0., 0.]])

In [30]:
nm.ones([3,4])

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [32]:
#Numpy - Linear Algebra

In [33]:
arr1 = np.random.randint([[2,3] , [4,5]])

In [34]:
arr2 = np.random.randint([[5,3] , [5,2]])

In [35]:
arr1

array([[1, 2],
       [2, 1]])

In [36]:
arr2

array([[0, 2],
       [4, 0]])

In [38]:
np.dot(arr1,arr2)

array([[8, 2],
       [4, 4]])

In [39]:
arr1@arr2

array([[8, 2],
       [4, 4]])