In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [3]:
type(l)

list

In [4]:
ar = np.array(l)

In [5]:
type(ar)

numpy.ndarray

In [6]:
ar

array([1, 2, 3, 4])

In [7]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
type(np.array([[1,2],[3,4]]))

numpy.ndarray

In [9]:
np.asarray(l)

array([1, 2, 3, 4])

In [10]:
type(np.asarray(l))

numpy.ndarray

In [11]:
a=[2,3,4]

In [12]:
np.asarray(a)

array([2, 3, 4])

In [13]:
b= np.matrix(l)

In [14]:
b

matrix([[1, 2, 3, 4]])

In [15]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [16]:
# matrix was not convert to pure array
# by default the matrix is subset of arraay

In [17]:
a=np.array(l)

In [18]:
a

array([1, 2, 3, 4])

In [20]:
c=a

In [21]:
c

array([1, 2, 3, 4])

In [22]:
a

array([1, 2, 3, 4])

In [23]:
c[0]

1

In [24]:
c[0]=100

In [25]:
c

array([100,   2,   3,   4])

In [26]:
a

array([100,   2,   3,   4])

In [27]:
a[3]=50

In [28]:
a

array([100,   2,   3,  50])

In [29]:
c

array([100,   2,   3,  50])

In [30]:
d=np.copy(a)

In [31]:
d

array([100,   2,   3,  50])

In [32]:
a[1]=400

In [33]:
a

array([100, 400,   3,  50])

In [34]:
d

array([100,   2,   3,  50])

In [37]:
np.fromfunction(lambda i,j : i==j,(3,3))

# for genrating the array at any time

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [38]:
np.fromfunction(lambda i,j : i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [41]:
iterable=(i*i for i in range(5))

In [43]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [45]:
np.fromstring('234 234',sep=' ')

array([234., 234.])

In [47]:
np.fromstring('4,5',sep=',')

array([4., 5.])

In [48]:
l=[2,3,4,5,6]

In [51]:
ar=np.array(l)

In [52]:
ar

array([2, 3, 4, 5, 6])

In [53]:
ar.ndim
# shoe the dimensional

1

In [54]:
ar2=np.array([[1,2,3,4],[5,6,7,8]])

In [55]:
ar2.ndim

2

In [56]:
ar.size

5

In [57]:
ar2.size

8

In [58]:
ar.shape

(5,)

In [60]:
ar2.shape
# 2 row and 4 columns

(2, 4)

In [61]:
ar.dtype

dtype('int32')

In [62]:
ar2.dtype

dtype('int32')

In [63]:
ar22 = np.array([(1.4,45,45) , (23,45,66)])

In [64]:
type(ar22)

numpy.ndarray

In [66]:
ar22.dtype

dtype('float64')

In [67]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [68]:
range(5)

range(0, 5)

In [70]:
list(range(5))

[0, 1, 2, 3, 4]

In [71]:
list(range(0.1 ,5))

TypeError: 'float' object cannot be interpreted as an integer

In [72]:
np.arange(2.3,5.6)
# jump the data by default 1

array([2.3, 3.3, 4.3, 5.3])

In [74]:
np.arange(2.3,5.6,.3)
# jump the data in between three range

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [75]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [76]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [77]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [78]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [79]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [81]:
ar4=np.zeros((3,4,2,3))

In [82]:
ar4.ndim

4

In [83]:
np.ones(4)

array([1., 1., 1., 1.])

In [84]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [85]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [86]:
on=np.ones((2,3,2))

In [87]:
on+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [88]:
on*6

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [89]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [90]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [91]:
np.linspace(2,4 , 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [92]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [100]:
arr = np.random.randn(3,4)
# genrate the random function 
# mean =0 std=1

In [96]:
arr

array([[ 1.99900333, -0.60361187, -2.07324   ,  1.10721111],
       [-0.01074759,  0.17572117,  1.35650366,  1.5512275 ],
       [ 0.04411033,  0.29541446, -0.03446482, -0.22214021]])

In [97]:
import pandas as pd

In [98]:
pd.DataFrame(arr)

0         1         2         3
0  1.999003 -0.603612 -2.073240  1.107211
1 -0.010748  0.175721  1.356504  1.551228
2  0.044110  0.295414 -0.034465 -0.222140

In [101]:
np.random.rand(3,4)
# genrate the random function 

array([[0.81933391, 0.78176337, 0.52512951, 0.79170015],
       [0.06279792, 0.14183248, 0.49150662, 0.19884718],
       [0.47577859, 0.78629932, 0.42872335, 0.56225327]])

In [103]:
np.random.randint(1,110,(3,4))
# genrate the random int

array([[ 79,  33,  17, 102],
       [ 37,  17,  88,  20],
       [ 20,  12,  80,  10]])

In [104]:
np.random.randint(1,110,(300,400))

array([[ 85,  81,  59, ...,  62,  19,  11],
       [ 76,  62,  23, ...,  35,  19,  28],
       [ 88, 105,  37, ...,  57,  90, 108],
       ...,
       [  5,   9,  91, ...,  20,  53,  12],
       [ 90,  41,  81, ...,   2,  69,  24],
       [  8,  25, 103, ...,  85,  71,  90]])

In [105]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv('bhiki.csv')

In [106]:
arr = np.random.rand(3,4)

In [107]:
arr

array([[0.74977414, 0.81930591, 0.60552573, 0.04634327],
       [0.21093138, 0.07660965, 0.10351714, 0.46939234],
       [0.75444269, 0.50774311, 0.09931836, 0.3931047 ]])

In [111]:
arr.reshape(2,6)

array([[0.74977414, 0.81930591, 0.60552573, 0.04634327, 0.21093138,
        0.07660965],
       [0.10351714, 0.46939234, 0.75444269, 0.50774311, 0.09931836,
        0.3931047 ]])

In [113]:
arr.reshape(6,-1)
# -ve ko chod dega just dekhga kitne data hai kese isko multiply kar ke value mileha
# 6*2=12

array([[0.74977414, 0.81930591],
       [0.60552573, 0.04634327],
       [0.21093138, 0.07660965],
       [0.10351714, 0.46939234],
       [0.75444269, 0.50774311],
       [0.09931836, 0.3931047 ]])

In [115]:
arr1=arr.reshape(6,-1)

In [116]:
arr1

array([[0.74977414, 0.81930591],
       [0.60552573, 0.04634327],
       [0.21093138, 0.07660965],
       [0.10351714, 0.46939234],
       [0.75444269, 0.50774311],
       [0.09931836, 0.3931047 ]])

In [117]:
arr1[1]

array([0.60552573, 0.04634327])

In [118]:
arr1[1][0]

0.6055257261937047

In [119]:
arr1[2:5]

array([[0.21093138, 0.07660965],
       [0.10351714, 0.46939234],
       [0.75444269, 0.50774311]])

In [120]:
arr1[2:5,1]

array([0.07660965, 0.46939234, 0.50774311])

In [121]:
arr1[2:5,0]

array([0.21093138, 0.10351714, 0.75444269])

In [123]:
arr=np.random.randint(1,100,(5,5))

In [124]:
arr

array([[69, 23, 74, 11, 13],
       [13, 71, 67, 55, 25],
       [24, 74, 25, 37, 23],
       [ 1, 56, 17, 85,  6],
       [23,  8, 51, 12, 85]])

In [125]:
arr>50

array([[ True, False,  True, False, False],
       [False,  True,  True,  True, False],
       [False,  True, False, False, False],
       [False,  True, False,  True, False],
       [False, False,  True, False,  True]])

In [126]:
arr[arr>50]

array([69, 74, 71, 67, 55, 74, 56, 85, 51, 85])

In [127]:
arr

array([[69, 23, 74, 11, 13],
       [13, 71, 67, 55, 25],
       [24, 74, 25, 37, 23],
       [ 1, 56, 17, 85,  6],
       [23,  8, 51, 12, 85]])

In [128]:
arr[2:4,[1,2]]

array([[74, 25],
       [56, 17]])

In [129]:
arr[0][0]

69

In [130]:
arr[0][0]=5000

In [131]:
arr

array([[5000,   23,   74,   11,   13],
       [  13,   71,   67,   55,   25],
       [  24,   74,   25,   37,   23],
       [   1,   56,   17,   85,    6],
       [  23,    8,   51,   12,   85]])

In [132]:
arr1 = np.random.randint(1,3,(3,3))

In [133]:
arr2 = np.random.randint(1,3,(3,3))

In [134]:
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [2, 1, 2]])

In [135]:
arr2

array([[1, 1, 1],
       [2, 2, 2],
       [1, 1, 1]])

In [136]:
arr1+arr2

array([[2, 2, 2],
       [3, 3, 3],
       [3, 2, 3]])

In [137]:
arr1-arr2

array([[ 0,  0,  0],
       [-1, -1, -1],
       [ 1,  0,  1]])

In [138]:
arr1/arr2

array([[1. , 1. , 1. ],
       [0.5, 0.5, 0.5],
       [2. , 1. , 2. ]])

In [139]:
arr1*arr2

array([[1, 1, 1],
       [2, 2, 2],
       [2, 1, 2]])

In [140]:
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [2, 1, 2]])

In [141]:
arr2

array([[1, 1, 1],
       [2, 2, 2],
       [1, 1, 1]])

In [142]:
# for metrix multiplication

In [143]:
arr1@arr2

array([[4, 4, 4],
       [4, 4, 4],
       [6, 6, 6]])

In [144]:
arr1/0

C:\Users\User\AppData\Local\Temp\ipykernel_4984\1510032488.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [145]:
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [2, 1, 2]])

In [146]:
arr1+100

array([[101, 101, 101],
       [101, 101, 101],
       [102, 101, 102]])

In [147]:
arr1**2

array([[1, 1, 1],
       [1, 1, 1],
       [4, 1, 4]], dtype=int32)

In [149]:
# Numpy broadcasting

In [151]:
arr=np.zeros((4,4))

In [152]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [153]:
row = np.array([1,2,3,4])

In [154]:
row.shape

(4,)

In [155]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [156]:
row.T

array([1, 2, 3, 4])

In [157]:
col=np.array([[1,2,3,4]])

In [158]:
col

array([[1, 2, 3, 4]])

In [159]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [160]:
col.T+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [162]:
arr1=np.random.randint(1,4,(3,4))

In [163]:
arr1

array([[1, 1, 1, 2],
       [1, 3, 3, 3],
       [1, 2, 2, 1]])

In [164]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.        , 1.41421356],
       [1.        , 1.73205081, 1.73205081, 1.73205081],
       [1.        , 1.41421356, 1.41421356, 1.        ]])

In [165]:
np.exp(arr1)

array([[ 2.71828183,  2.71828183,  2.71828183,  7.3890561 ],
       [ 2.71828183, 20.08553692, 20.08553692, 20.08553692],
       [ 2.71828183,  7.3890561 ,  7.3890561 ,  2.71828183]])

In [166]:
np.log10(arr1)

array([[0.        , 0.        , 0.        , 0.30103   ],
       [0.        , 0.47712125, 0.47712125, 0.47712125],
       [0.        , 0.30103   , 0.30103   , 0.        ]])